//! Embed the static product UI into the `ocg` binary.
//!
//! The export is optional for runtime-only development builds, but when an
//! export is present it is represented by a deterministic generated asset
//! table. Release builds therefore ship the exact UI that the binary serves.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

const EXCLUDED_NAMES: &[&str] = &[".DS_Store", "Thumbs.db"];
const EXCLUDED_SUFFIXES: &[&str] = &[".map"];

fn absolute(path: &Path) -> PathBuf {
    if path.is_absolute() {
        return path.to_path_buf();
    }
    PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap_or_else(|| ".".into())).join(path)
}

fn main() {
    println!("cargo:rerun-if-env-changed=OCG_UI_DIR");
    println!("cargo:rerun-if-env-changed=OCG_SKIP_UI");
    println!("cargo:rerun-if-changed=frontend/next.config.ts");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/out");

    let root = absolute(
        &std::env::var_os("OCG_UI_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("frontend/out")),
    );
    let skip = std::env::var("OCG_SKIP_UI").is_ok_and(|value| value == "1");
    let mut assets = BTreeMap::new();
    let mut ui_version = String::new();
    let note = if skip {
        "embedding was disabled with OCG_SKIP_UI=1".to_string()
    } else {
        if let Err(reason) = collect(&root, &mut assets, &mut ui_version) {
            // Runtime-only builds remain possible without Node. A packaged UI
            // is validated separately by the release workflow.
            eprintln!("cargo:warning=OCG UI was not embedded: {reason}");
            assets.clear();
        }
        if assets.is_empty() {
            format!("no product UI embedded from {}", root.display())
        } else {
            format!("{} asset(s) embedded from {}", assets.len(), root.display())
        }
    };

    let package_version = std::env::var("CARGO_PKG_VERSION").unwrap_or_default();
    let ui_version = if ui_version.is_empty() {
        package_version.clone()
    } else {
        ui_version
    };
    let mut generated = String::from("// @generated by build.rs; do not edit.\n");
    generated.push_str(&format!(
        "pub const PACKAGED: bool = {};\n",
        !assets.is_empty()
    ));
    generated.push_str(&format!("pub const BUILD_NOTE: &str = {:?};\n", note));
    generated.push_str(&format!("pub const UI_VERSION: &str = {:?};\n", ui_version));
    generated.push_str(&format!(
        "pub const BACKEND_VERSION: &str = {:?};\n",
        package_version
    ));
    generated.push_str("pub const ASSETS: &[(&str, &[u8])] = &[\n");
    for (relative, path) in assets {
        generated.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            relative,
            path.display().to_string()
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out.join("ui_assets.rs"), generated).expect("write generated UI asset table");
}

fn collect(
    root: &Path,
    assets: &mut BTreeMap<String, PathBuf>,
    ui_version: &mut String,
) -> Result<(), String> {
    if !root.is_dir() {
        return Err(format!(
            "UI export directory {} does not exist",
            root.display()
        ));
    }
    let mut stack = vec![root.to_path_buf()];
    while let Some(directory) = stack.pop() {
        for entry in fs::read_dir(&directory).map_err(|error| error.to_string())? {
            let entry = entry.map_err(|error| error.to_string())?;
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().into_owned();
            if name.starts_with('.') || EXCLUDED_NAMES.contains(&name.as_str()) {
                continue;
            }
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if EXCLUDED_SUFFIXES
                .iter()
                .any(|suffix| name.ends_with(suffix))
            {
                continue;
            }
            let relative = path
                .strip_prefix(root)
                .map_err(|_| "asset escaped the export root".to_string())?
                .to_string_lossy()
                .replace('\\', "/");
            if relative == "ocg-ui.json" {
                if let Ok(text) = fs::read_to_string(&path) {
                    *ui_version = extract_version(&text).unwrap_or_default();
                }
            }
            assets.insert(relative, absolute(&path));
        }
    }
    if !assets.contains_key("index.html") {
        return Err("UI export has no index.html".to_string());
    }
    Ok(())
}

fn extract_version(text: &str) -> Option<String> {
    let rest = text.split_once("\"version\"")?.1.trim_start();
    let rest = rest.strip_prefix(':')?.trim_start().strip_prefix('"')?;
    Some(rest.split('"').next()?.to_string())
}
